version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '123'
      MARIADB_DATABASE: 'test'
    ports:
      - '3306:3306'

  app:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    command: pnpm dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
